# Generated by Django 3.2.4 on 2021-06-07 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learndjango', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
